require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JinianItemsController do

  # This should return the minimal set of attributes required to create a valid
  # JinianItem. As you add validations to JinianItem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "jinian_cate" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JinianItemsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all jinian_items as @jinian_items" do
      jinian_item = JinianItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:jinian_items).should eq([jinian_item])
    end
  end

  describe "GET show" do
    it "assigns the requested jinian_item as @jinian_item" do
      jinian_item = JinianItem.create! valid_attributes
      get :show, {:id => jinian_item.to_param}, valid_session
      assigns(:jinian_item).should eq(jinian_item)
    end
  end

  describe "GET new" do
    it "assigns a new jinian_item as @jinian_item" do
      get :new, {}, valid_session
      assigns(:jinian_item).should be_a_new(JinianItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested jinian_item as @jinian_item" do
      jinian_item = JinianItem.create! valid_attributes
      get :edit, {:id => jinian_item.to_param}, valid_session
      assigns(:jinian_item).should eq(jinian_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new JinianItem" do
        expect {
          post :create, {:jinian_item => valid_attributes}, valid_session
        }.to change(JinianItem, :count).by(1)
      end

      it "assigns a newly created jinian_item as @jinian_item" do
        post :create, {:jinian_item => valid_attributes}, valid_session
        assigns(:jinian_item).should be_a(JinianItem)
        assigns(:jinian_item).should be_persisted
      end

      it "redirects to the created jinian_item" do
        post :create, {:jinian_item => valid_attributes}, valid_session
        response.should redirect_to(JinianItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved jinian_item as @jinian_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        JinianItem.any_instance.stub(:save).and_return(false)
        post :create, {:jinian_item => { "jinian_cate" => "invalid value" }}, valid_session
        assigns(:jinian_item).should be_a_new(JinianItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        JinianItem.any_instance.stub(:save).and_return(false)
        post :create, {:jinian_item => { "jinian_cate" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested jinian_item" do
        jinian_item = JinianItem.create! valid_attributes
        # Assuming there are no other jinian_items in the database, this
        # specifies that the JinianItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        JinianItem.any_instance.should_receive(:update_attributes).with({ "jinian_cate" => "" })
        put :update, {:id => jinian_item.to_param, :jinian_item => { "jinian_cate" => "" }}, valid_session
      end

      it "assigns the requested jinian_item as @jinian_item" do
        jinian_item = JinianItem.create! valid_attributes
        put :update, {:id => jinian_item.to_param, :jinian_item => valid_attributes}, valid_session
        assigns(:jinian_item).should eq(jinian_item)
      end

      it "redirects to the jinian_item" do
        jinian_item = JinianItem.create! valid_attributes
        put :update, {:id => jinian_item.to_param, :jinian_item => valid_attributes}, valid_session
        response.should redirect_to(jinian_item)
      end
    end

    describe "with invalid params" do
      it "assigns the jinian_item as @jinian_item" do
        jinian_item = JinianItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        JinianItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => jinian_item.to_param, :jinian_item => { "jinian_cate" => "invalid value" }}, valid_session
        assigns(:jinian_item).should eq(jinian_item)
      end

      it "re-renders the 'edit' template" do
        jinian_item = JinianItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        JinianItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => jinian_item.to_param, :jinian_item => { "jinian_cate" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested jinian_item" do
      jinian_item = JinianItem.create! valid_attributes
      expect {
        delete :destroy, {:id => jinian_item.to_param}, valid_session
      }.to change(JinianItem, :count).by(-1)
    end

    it "redirects to the jinian_items list" do
      jinian_item = JinianItem.create! valid_attributes
      delete :destroy, {:id => jinian_item.to_param}, valid_session
      response.should redirect_to(jinian_items_url)
    end
  end

end
