require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SiteCatesController do

  # This should return the minimal set of attributes required to create a valid
  # SiteCate. As you add validations to SiteCate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SiteCatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all site_cates as @site_cates" do
      site_cate = SiteCate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:site_cates).should eq([site_cate])
    end
  end

  describe "GET show" do
    it "assigns the requested site_cate as @site_cate" do
      site_cate = SiteCate.create! valid_attributes
      get :show, {:id => site_cate.to_param}, valid_session
      assigns(:site_cate).should eq(site_cate)
    end
  end

  describe "GET new" do
    it "assigns a new site_cate as @site_cate" do
      get :new, {}, valid_session
      assigns(:site_cate).should be_a_new(SiteCate)
    end
  end

  describe "GET edit" do
    it "assigns the requested site_cate as @site_cate" do
      site_cate = SiteCate.create! valid_attributes
      get :edit, {:id => site_cate.to_param}, valid_session
      assigns(:site_cate).should eq(site_cate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SiteCate" do
        expect {
          post :create, {:site_cate => valid_attributes}, valid_session
        }.to change(SiteCate, :count).by(1)
      end

      it "assigns a newly created site_cate as @site_cate" do
        post :create, {:site_cate => valid_attributes}, valid_session
        assigns(:site_cate).should be_a(SiteCate)
        assigns(:site_cate).should be_persisted
      end

      it "redirects to the created site_cate" do
        post :create, {:site_cate => valid_attributes}, valid_session
        response.should redirect_to(SiteCate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved site_cate as @site_cate" do
        # Trigger the behavior that occurs when invalid params are submitted
        SiteCate.any_instance.stub(:save).and_return(false)
        post :create, {:site_cate => { "name" => "invalid value" }}, valid_session
        assigns(:site_cate).should be_a_new(SiteCate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SiteCate.any_instance.stub(:save).and_return(false)
        post :create, {:site_cate => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested site_cate" do
        site_cate = SiteCate.create! valid_attributes
        # Assuming there are no other site_cates in the database, this
        # specifies that the SiteCate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SiteCate.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => site_cate.to_param, :site_cate => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested site_cate as @site_cate" do
        site_cate = SiteCate.create! valid_attributes
        put :update, {:id => site_cate.to_param, :site_cate => valid_attributes}, valid_session
        assigns(:site_cate).should eq(site_cate)
      end

      it "redirects to the site_cate" do
        site_cate = SiteCate.create! valid_attributes
        put :update, {:id => site_cate.to_param, :site_cate => valid_attributes}, valid_session
        response.should redirect_to(site_cate)
      end
    end

    describe "with invalid params" do
      it "assigns the site_cate as @site_cate" do
        site_cate = SiteCate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SiteCate.any_instance.stub(:save).and_return(false)
        put :update, {:id => site_cate.to_param, :site_cate => { "name" => "invalid value" }}, valid_session
        assigns(:site_cate).should eq(site_cate)
      end

      it "re-renders the 'edit' template" do
        site_cate = SiteCate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SiteCate.any_instance.stub(:save).and_return(false)
        put :update, {:id => site_cate.to_param, :site_cate => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested site_cate" do
      site_cate = SiteCate.create! valid_attributes
      expect {
        delete :destroy, {:id => site_cate.to_param}, valid_session
      }.to change(SiteCate, :count).by(-1)
    end

    it "redirects to the site_cates list" do
      site_cate = SiteCate.create! valid_attributes
      delete :destroy, {:id => site_cate.to_param}, valid_session
      response.should redirect_to(site_cates_url)
    end
  end

end
